## 张量的创建

In [2]:
import torch
import numpy as np

In [2]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [3]:
torch.tensor(np.arange(15).reshape(3,5))

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]], dtype=torch.int32)

In [4]:
torch.empty([3,4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [5]:
torch.ones([3,4])

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [6]:
torch.zeros([3,4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

## 张量的属性和方法

In [7]:
a = torch.tensor([[[1]]])

In [8]:
a.item()

1

In [58]:
t2 = torch.tensor([[[1,2]]])

In [61]:
a1 = t2.numpy()

In [63]:
a1.shape

(1, 1, 2)

In [60]:
t2.size()

torch.Size([1, 1, 2])

In [9]:
t = a.numpy()

In [10]:
type(t)

numpy.ndarray

In [11]:
a.shape

torch.Size([1, 1, 1])

In [12]:
a.size()

torch.Size([1, 1, 1])

In [13]:
a = torch.tensor(np.arange(30).reshape(3,2,5))

In [14]:
a

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]], dtype=torch.int32)

In [15]:
a.size(1)

2

In [16]:
a.view([2,3,5])

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14]],

        [[15, 16, 17, 18, 19],
         [20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]], dtype=torch.int32)

In [17]:
b = torch.tensor(np.arange(15).reshape(3,5))

In [18]:
b

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]], dtype=torch.int32)

In [19]:
b.transpose(0,1)  #直接交换行和列

tensor([[ 0,  5, 10],
        [ 1,  6, 11],
        [ 2,  7, 12],
        [ 3,  8, 13],
        [ 4,  9, 14]], dtype=torch.int32)

In [20]:
b.view(5,-1) #把b展开之后等分为5分

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]], dtype=torch.int32)

In [21]:
a  #[3,2,5]

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]], dtype=torch.int32)

In [22]:
a.transpose(0,1)  #[2,3,5]

tensor([[[ 0,  1,  2,  3,  4],
         [10, 11, 12, 13, 14],
         [20, 21, 22, 23, 24]],

        [[ 5,  6,  7,  8,  9],
         [15, 16, 17, 18, 19],
         [25, 26, 27, 28, 29]]], dtype=torch.int32)

In [3]:
arr = torch.tensor(np.arange(12).reshape((2,2,3)))
arr

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]], dtype=torch.int32)

In [68]:
arr.transpose(0,1)

tensor([[[ 0,  1,  2,  3],
         [12, 13, 14, 15]],

        [[ 4,  5,  6,  7],
         [16, 17, 18, 19]],

        [[ 8,  9, 10, 11],
         [20, 21, 22, 23]]], dtype=torch.int32)

In [71]:
arr.permute(1,0,2)

tensor([[[ 0,  1,  2,  3],
         [12, 13, 14, 15]],

        [[ 4,  5,  6,  7],
         [16, 17, 18, 19]],

        [[ 8,  9, 10, 11],
         [20, 21, 22, 23]]], dtype=torch.int32)

In [6]:
arr.transpose(0,2)

tensor([[[ 0,  6],
         [ 3,  9]],

        [[ 1,  7],
         [ 4, 10]],

        [[ 2,  8],
         [ 5, 11]]], dtype=torch.int32)

In [7]:
arr.permute(2,1,0)

tensor([[[ 0,  6],
         [ 3,  9]],

        [[ 1,  7],
         [ 4, 10]],

        [[ 2,  8],
         [ 5, 11]]], dtype=torch.int32)

In [4]:
arr.transpose(1,2)

tensor([[[ 0,  3],
         [ 1,  4],
         [ 2,  5]],

        [[ 6,  9],
         [ 7, 10],
         [ 8, 11]]], dtype=torch.int32)

In [5]:
arr.permute(0,2,1)

tensor([[[ 0,  3],
         [ 1,  4],
         [ 2,  5]],

        [[ 6,  9],
         [ 7, 10],
         [ 8, 11]]], dtype=torch.int32)

In [23]:
b[1,:]

tensor([5, 6, 7, 8, 9], dtype=torch.int32)

In [24]:
b[1]

tensor([5, 6, 7, 8, 9], dtype=torch.int32)

In [25]:
b

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]], dtype=torch.int32)

In [26]:
b[:,1]

tensor([ 1,  6, 11], dtype=torch.int32)

In [27]:
b[:,1] = 100

In [65]:
torch.tensor([1],dtype=torch.double)

tensor([1.], dtype=torch.float64)

In [28]:
b

tensor([[  0, 100,   2,   3,   4],
        [  5, 100,   7,   8,   9],
        [ 10, 100,  12,  13,  14]], dtype=torch.int32)

In [29]:
b[-1,-1] = 100

In [30]:
b

tensor([[  0, 100,   2,   3,   4],
        [  5, 100,   7,   8,   9],
        [ 10, 100,  12,  13, 100]], dtype=torch.int32)

In [31]:
b[-1,-1]

tensor(100, dtype=torch.int32)

In [32]:
c = {100:10,20:10}

In [33]:
c[b.numpy()[-1,-1]]

10

In [34]:
b

tensor([[  0, 100,   2,   3,   4],
        [  5, 100,   7,   8,   9],
        [ 10, 100,  12,  13, 100]], dtype=torch.int32)

In [35]:
b.max(dim=-1)[-1]

tensor([1, 1, 1])

In [36]:
b

tensor([[  0, 100,   2,   3,   4],
        [  5, 100,   7,   8,   9],
        [ 10, 100,  12,  13, 100]], dtype=torch.int32)

In [37]:
torch.FloatTensor([1,2,3]).dtype

torch.float32

In [38]:
a = torch.tensor([1,2,3])

In [39]:
torch.ones([2,3],dtype=torch.float32)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [40]:
b

tensor([[  0, 100,   2,   3,   4],
        [  5, 100,   7,   8,   9],
        [ 10, 100,  12,  13, 100]], dtype=torch.int32)

In [41]:
b.new_ones(size=b.size())

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.int32)

In [42]:
b.zero_()

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int32)

In [43]:
b

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int32)

In [44]:
b.add(1)

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.int32)

In [45]:
b.add_(1)

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.int32)

In [46]:
b

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.int32)

## cuda类型的tensor

In [75]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu") 

In [76]:
torch.cuda.is_available()

True

In [77]:
device

device(type='cuda')

In [78]:
a.device

device(type='cuda', index=0)

In [79]:
a = a.to(device)

In [80]:
a

tensor([1, 2, 3], device='cuda:0')

In [52]:
a.cpu().device

device(type='cpu')

In [53]:
b = torch.tensor([0,0,0])

In [54]:
b

tensor([0, 0, 0])

In [55]:
a+b.to(device)

tensor([1, 2, 3], device='cuda:0')

In [56]:
a.cpu().numpy()

array([1, 2, 3], dtype=int64)